// Generated by CoffeeScript 1.9.3
require("!style!css!./todo.css");

document.addEventListener('DOMContentLoaded', function() {
  'use strict';
  
  var ref, todo;
  ref = new Firebase('https://amber-fire-5590.firebaseio.com');
  todo = new Vue({
    el: '#todo',
    data: {
      todos: [
        {
          done: false,
          content: 'Loading data from Firebase...'
        }
      ]
    },
    methods: {
      addTo: function() {
        ref.push({
          done: false,
          content: document.getElementById('newTodo').value
        });
        return document.getElementById('newTodo').value = '';
      },
      clearCompleted: function() {
        return _.each(todo.$get('todos'), function(t, todoKey) {
          if (t && t.done) {
            return ref.child(todoKey).remove();
          }
        });
      },
      madeDone: function() {
        return ref.child('done').set({
          done: true
        });
      }
    }
  });
  return ref.on('value', function(snapshot) {
    return todo.$set('todos', snapshot.val());
  });
});
